import type { Metadata } from "next"
import { notoSans, tiltWarp } from "@/utils/fonts"
import "./globals.css"
import "./_css/animation.css"
import "./_css/block.css"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={`${notoSans.variable} ${tiltWarp.variable}`}>
                {children}
            </body>
        </html>
    )
}
